#!/usr/bin/python
import sys
import os

def createFile(fname, content):
    f = open(fname, "w")
    f.write(content)
    f.close()

if __name__ == "__main__":
    if len(sys.argv) == 1:
        print "Class name required."
        exit(1)
    cname = sys.argv[1]
    utag = cname.upper() + "_H"
    hc = "#ifndef %s\n#define %s\nBEGIN_NAMESPACE(cgserver)\n    class %s{\n    public:\n        %s();\n        ~%s();\n    };\nEND_NAMESPACE\n#endif\n" %\
         (utag, utag, cname, cname, cname)
    createFile(cname.lower() + ".h", hc)
    cppc = '#include "%s.h"\nBEGIN_NAMESPACE(cgserver)\n    %s::%s(){\n    }\n\n    %s::~%s(){\n    }\nEND_NAMESPACE' %\
           (cname.lower(), cname, cname, cname, cname)
    createFile(cname.lower() + ".cpp", cppc)    

    
