#!/usr/bin/python
import sys
import os

def createFile(fname, content):
    f = open(fname, "w")
    f.write(content)
    f.close()

if __name__ == "__main__":
    if len(sys.argv) == 1:
        print "Class name required."
        exit(1)
    cname = sys.argv[1]
    namespace = "cgserver"
    if len(sys.argv) >2:
        namespace = sys.argv[2]
    utag = cname.upper() + "_H"
    hc = "#ifndef %s\n#define %s\n\n\n\nBEGIN_NAMESPACE(%s)\n\nclass %s{\n public:\n    %s();\n    ~%s();\n};\n\nEND_NAMESPACE\n#endif\n" %\
         (utag, utag, namespace, cname, cname, cname)
    createFile(cname.lower() + ".h", hc)
    cppc = '#include "%s.h"\n\nBEGIN_NAMESPACE(%s)\n\n%s::%s(){\n}\n\n%s::~%s(){\n}\n\nEND_NAMESPACE' %\
           (cname.lower(), namespace, cname, cname, cname, cname)
    createFile(cname.lower() + ".cpp", cppc)    

    
